-- MySQL Script generated by MySQL Workbench
-- Thu Sep  5 20:29:32 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`parentesco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`parentesco` (
  `idParentesco` INT NOT NULL AUTO_INCREMENT,
  `nombreParentesco` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idParentesco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`persona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `nombrePersona` VARCHAR(45) NOT NULL,
  `apellidosPersona` VARCHAR(45) NOT NULL,
  `fechaNacimientoPersona` DATE NULL,
  `generoPersona` VARCHAR(3) NULL,
  `parentesco_idParentesco` INT NOT NULL,
  PRIMARY KEY (`idPersona`),
  INDEX `fk_persona_parentesco1_idx` (`parentesco_idParentesco` ASC) VISIBLE,
  CONSTRAINT `fk_persona_parentesco1`
    FOREIGN KEY (`parentesco_idParentesco`)
    REFERENCES `mydb`.`parentesco` (`idParentesco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hobbie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hobbie` (
  `idHobbie` INT NOT NULL AUTO_INCREMENT,
  `nombreHobbie` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idHobbie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`persona_has_hobbie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`persona_has_hobbie` (
  `persona_idPersona` INT NOT NULL,
  `hobbie_idHobbie` INT NOT NULL,
  PRIMARY KEY (`persona_idPersona`, `hobbie_idHobbie`),
  INDEX `fk_persona_has_hobbie_hobbie1_idx` (`hobbie_idHobbie` ASC) VISIBLE,
  INDEX `fk_persona_has_hobbie_persona_idx` (`persona_idPersona` ASC) VISIBLE,
  CONSTRAINT `fk_persona_has_hobbie_persona`
    FOREIGN KEY (`persona_idPersona`)
    REFERENCES `mydb`.`persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_persona_has_hobbie_hobbie1`
    FOREIGN KEY (`hobbie_idHobbie`)
    REFERENCES `mydb`.`hobbie` (`idHobbie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
